### ISSUE TITLE
Support passing in directory where to save the images to 

### ISSUE THREAD

**Issue by nikitavoloboev** [johnletey/dl-imgs#1]
Currently it by default saves images to `/.imgs` dir.

I would like to be able to save the images to a certain directory by passing it in additionally having the option to name the directory where the images will be saved in.

For example have it support something like this:

`dl-imgs -p ~/Dropbox/Write/knowledge -loc ~/Dropbox/History/wiki\ images\ (April\ 2019)`

So it loads all images from the dir mentioned in -p flag to dir mentioned in -loc flag.

**Comment by johnletey** [comment]
@nikitavoloboev This is a great idea ... I’ll try to have this implemented within the next few days

**Comment by johnletey** [comment]
@nikitavoloboev I’ve implemented this ... does it work fine on your end?

**Comment by nikitavoloboev** [comment]
nope

`❯ dl-imgs -p ~/Dropbox/Write/knowledge -loc ~/Desktop
dl-imgs: error: unexpected /Users/nikivi/Desktop, try --help`

**Comment by nikitavoloboev** [comment]
I did go get new version

**Comment by johnletey** [comment]
@nikitavoloboev Yes, because Kingpin doesn’t let you shorten a command to a string (only chars) ... the flag is ‘—location’ or ‘-l’

I can open up a new feature request in Kingpin if you want this to be ‘-loc’

**Comment by nikitavoloboev** [comment]
Didn't know as there are no docs in the readme :D

**Comment by johnletey** [comment]
Fair point ... working now?

**Comment by nikitavoloboev** [comment]
Ok I tried

```
❯ dl-imgs -p ~/Dropbox/Write/knowledge -l ~/Desktop
575 file(s) found in path '/Users/nikivi/Dropbox/Write/knowledge'
Done. Check the folder '/Users/nikivi/Desktop/images' for all the downloaded images
```

Nothing shows

Then 

```
❯ dl-imgs -p ~/Dropbox/Write/knowledge -l ~/Desktop/images
575 file(s) found in path '/Users/nikivi/Dropbox/Write/knowledge'
Done. Check the folder '/Users/nikivi/Desktop/images' for all the downloaded images
```

No `images` folder created.

**Comment by nikitavoloboev** [comment]
> can open up a new feature request in Kingpin if you want this to be `-loc`

No need. `-l` or `-loc` is fine. Just readme should be updated

**Comment by johnletey** [comment]
@nikitavoloboev What your experiencing is the effects of using Go Concurrency (what makes this tool extremely fast): even though the program is finished in the command line, your computer is still downloading images in the background. I need to figure out how to fix this. You should see the images now in your desktop.

> I thought it would create default `imgs` folder in ~/Desktop

I didn't implement it this way. It will default to `./imgs` if nothing is passed in, and it will download the images to whatever directory that was passed in

> The `--help` is wrong/confusing as I saw `--loc` there although it does have two dashes

Sorry, I misspoke before.

Hopefully this helps clear things up, I'll investigate this further in the morning

**Comment by nikitavoloboev** [comment]
> You should see the images now in your desktop.

Still no images

**Comment by nikitavoloboev** [comment]
> It will default to `./imgs` if nothing is passed in

I would not make the folder hidden. There is no need for it.

**Comment by johnletey** [comment]
> I would not make the folder hidden.

The folder isn't hidden ... that would be `./.imgs`

`./` is the current directory ... `./imgs` is the `imgs` (not hidden) in the current directory

**Comment by nikitavoloboev** [comment]
Oh my bad. Makes sense then. :)

**Comment by johnletey** [comment]
> Still no images.

This is so weird ... I'll make sure to look into this in the morning
